name: CI Format, Typecheck and Lint

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  build:
    name: Format, Lint and Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # lfs: true
      # - name: Checkout LFS objects
      #   run: git lfs checkout

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Install deps
        run: bun i

      - name: Lint
        run: |
          bun run format:check
          bun run lint

      # - name: Run test
      #   run: bun run test
